Repository feelpp/antora-ui, pull requests merged in 2023-04, with the labels that each got.

#9 resolves #8: add support for github action
  .github/workflows/ci.yml
Labels: enhancement

#11 resolves #10: add release step
  .github/workflows/ci.yml
Labels: documentation, enhancement

#20 Fix social links and reorder items in header
  src/css/header.css
  src/css/vars.css
  src/img/octicons-16.svg
  src/img/slack-icon.svg
  src/partials/header-content.hbs
Labels: :sparkles: enhancement

#23 Toolbar redesign
  src/css/toolbar.css
  src/img/jupyter-logo.svg
  src/img/octicons-16.svg
  src/img/pdf.svg
  src/partials/header-content.hbs
  src/partials/toc.hbs
  src/partials/toolbar-downloads.hbs
  src/partials/toolbar-fullscreen.hbs
  src/partials/toolbar-github.hbs
  src/partials/toolbar.hbs
Labels: :sparkles: enhancement

#26 Simplify pseudocode syntax
  preview-src/index.adoc
  preview-src/pseudocode.adoc
  src/js/12-pseudocode.js
  src/partials/footer-scripts.hbs
  src/partials/head-meta.hbs
Labels: :sparkles: enhancement

#25 Dynamic download links
  gulp.d/tasks/build-preview-pages.js
  src/css/header.css
  src/helpers/get-install-page.js
  src/partials/header-content.hbs
Labels: :sparkles: enhancement
